[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules","lib"]
test = "Tests"
cache_path = "forge-cache"
solc = "0.8.24"
optimizer = true
optimizer_runs = 20
evm_version ="shanghai"
[invariant]
fail_on_revert = false
eth-rpc-url = "https://mainnet.infura.io/v3/PUT_YOUR_INFURA_KEY"
fs_permissions = [{ access = "read-write", path = "./"}]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[fuzz]
runs = 5
depth = 5
max_test_rejects = 20
[rpc_endpoints]
goerli = "https://goerli.infura.io/v3/PUT_YOUR_INFURA_KEY"
mainnet = "https://mainnet.infura.io/v3/PUT_YOUR_INFURA_KEY"
arbitrum = "https://arbitrum-mainnet.infura.io/v3/PUT_YOUR_INFURA_KEY"
